baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Marshcode'
Theme = 'mainroad'

[Params]
    customCSS = ["/hugo_static/css/custom.css"]
    mainSections = ['post']

[Params.widgets.social]
  linkedin = "daviddmarsh"
  github = "marshcode"
  email = "davidmarsh@marshcode.com"