baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Marshcode'
Theme = 'mainroad'

[Params]
    customCSS = ["/hugo_static/css/custom.css"]
    mainSections = ['post']

[Params.logo]
  image = "hugo_static/img/avatar.png" # Logo image. Path relative to "static"
  title = "Marshcode" # Logo title, otherwise will use site title
  subtitle = "Personal Project Showcase" # Logo subtitle

[Params.sidebar]
  home = false # Configure layout for home page
  list = false  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["project_nav"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets.social]
  linkedin = "daviddmarsh"
  github = "marshcode"
  email = "davidmarsh@marshcode.com"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Author]
  name = "David Marsh"
  bio = "I am a computer programmer in Massachusetts. My professional work is mostly back-end stuff. That's why all of my side projects have a visual component to them."
  avatar = "hugo_static/img/avatar.png"