baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Marshcode'
Theme = 'mainroad'

[Params]
    customCSS = ["/hugo_static/css/custom.css"]
    mainSections = ['post']

[Params.widgets.social]
  linkedin = "daviddmarsh"
  github = "marshcode"
  email = "davidmarsh@marshcode.com"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Author]
  name = "David Marsh"
  bio = "I am a computer programmer in Massachusetts. My professional work is mostly back-end stuff. That's why all of my side projects have a visual component to them."
  avatar = "hugo_static/img/avatar.png"